name: 'lw-scanner'
description: 'Lacework Inline Scanner'
author: 'Tim Arenz'
inputs:
  image_name:
    description: 'Name of the container image you want to scan, for example, node'
    required: true
  image_tag:
    description: 'Tag of the container image you want to scan, for example, 12.18.2-alpine'
    required: true
  fail_if_critical_vulnerabilities_found:
    description: 'Fail action if critical vulnerabilities are found.'
    required: false
    default: 'true'
  fail_if_high_vulnerabilities_found:
    description: 'Fail action if high vulnerabilities are found.'
    required: false
    default: 'true'
  fail_if_medium_vulnerabilities_found:
    description: 'Fail action if medium vulnerabilities are found.'
    required: false
    default: 'true'
  fail_if_low_vulnerabilities_found:
    description: 'Fail action if low vulnerabilities are found.'
    required: false
    default: 'false'
  fail_if_info_vulnerabilities_found:
    description: 'Fail action if info vulnerabilities are found.'
    required: false
    default: 'false'
  fail_only_if_vulnerabilities_fixable:
    description: 'Only fail action if found vulnerabilities are fixable.'
    required: false
    default: 'false'
  scan_library_packages:
    description: 'Scan for packages vulnerabilities'
    required: false
    default: 'false'
  save_results_in_lacework:
    description: 'Save scan results in Lacework'
    required: false
    default: 'true'
  save_build_report:
    description: 'Save scan results in html file as workflow artifact'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image_name }}
    - ${{ inputs.image_tag }}
    - ${{ inputs.fail_if_critical_vulnerabilities_found }}
    - ${{ inputs.fail_if_high_vulnerabilities_found }}
    - ${{ inputs.fail_if_medium_vulnerabilities_found }}
    - ${{ inputs.fail_if_low_vulnerabilities_found }}
    - ${{ inputs.fail_if_info_vulnerabilities_found }}
    - ${{ inputs.fail_only_if_vulnerabilities_fixable }}
    - ${{ inputs.scan_library_packages }}
    - ${{ inputs.save_results_in_lacework }}
    - ${{ inputs.save_build_report }}
branding:
  icon: 'alert-triangle'
  color: 'blue'
