name: "lw-scanner"
description: "Lacework Inline Scanner"
author: "Tim Arenz"
inputs:
  image_name:
    description: "Name of the container image you want to scan, for example, node"
    required: true
  image_tag:
    description: "Tag of the container image you want to scan, for example, 12.18.2-alpine"
    required: true
  fail_if_critical_vulnerabilities_found:
    description: "Fail action if critical vulnerabilities are found."
    required: false
    default: "true"
  fail_if_high_vulnerabilities_found:
    description: "Fail action if high vulnerabilities are found."
    required: false
    default: "true"
  fail_if_medium_vulnerabilities_found:
    description: "Fail action if medium vulnerabilities are found."
    required: false
    default: "true"
  fail_if_low_vulnerabilities_found:
    description: "Fail action if low vulnerabilities are found."
    required: false
    default: "false"
  fail_if_info_vulnerabilities_found:
    description: "Fail action if info vulnerabilities are found."
    required: false
    default: "false"
  fail_only_if_vulnerabilities_fixable:
    description: "Only fail action if found vulnerabilities are fixable."
    required: false
    default: "false"
  save_html_report:
    description: "Save scan results HTML report as workflow artifact"
    required: false
    default: "false"
  html_report_file_name:
    description: "Specify custom file name for the HTML report, by default the name is OS_TYPE-IMAGE_DIGEST_SHA256.html"
    required: false
    default: ""
  use_policy:
    description: "Use Lacework policy management feature (beta). This will ignore all `fail_...` parameters."
    required: true
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.image_name }}
    - ${{ inputs.image_tag }}
    - ${{ inputs.fail_if_critical_vulnerabilities_found }}
    - ${{ inputs.fail_if_high_vulnerabilities_found }}
    - ${{ inputs.fail_if_medium_vulnerabilities_found }}
    - ${{ inputs.fail_if_low_vulnerabilities_found }}
    - ${{ inputs.fail_if_info_vulnerabilities_found }}
    - ${{ inputs.fail_only_if_vulnerabilities_fixable }}
    - ${{ inputs.save_html_report }}
    - ${{ inputs.html_report_file_name }}
    - ${{ inputs.use_policy }}
branding:
  icon: "alert-triangle"
  color: "blue"
