name: test-action
on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    env:
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
      LW_SCANNER_SAVE_RESULTS: false
      LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
      LW_SCANNER_DISABLE_UPDATES: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker image pull node:12.18.2-alpine

      - name: lw-scanner
        uses: timarenz/lw-scanner-action@main
        with:
          image_name: node
          image_tag: 12.18.2-alpine
          fail_if_critical_vulnerabilities_found: false
          fail_if_high_vulnerabilities_found: false
          fail_if_medium_vulnerabilities_found: false
          fail_if_low_vulnerabilities_found: false
          fail_if_info_vulnerabilities_found: false
          fail_only_if_vulnerabilities_fixable: false
          save_html_report: true
          # html_report_file_name: myreport.html
