name: test-action
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    env:
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        use: docker image pull node:12.18.2-alpine

      # - name: lw-scanner
      #   uses: timarenz/lw-scanner-action@v0.0.6
      #   with:
      #     image_name: nodegoat
      #     image_tag: ${{ env.GHA_SHA }}
      #     fail_only_if_vulnerabilities_fixable: true