name: test-action-policy
on: [push, workflow_dispatch]

jobs:
  test-action-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker image pull ghcr.io/timarenz/vulnerable-container:v0.0.1

      - name: lw-scanner
        uses: ./
        continue-on-error: true
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN_POLICY }}
          IMAGE_NAME: ghcr.io/timarenz/vulnerable-container
          IMAGE_TAG: v0.0.1
          SAVE_BUILD_REPORT: true
          BUILD_REPORT_FILE_NAME: report.html
          USE_POLICY: true
