name: test-action
on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker image pull ghcr.io/timarenz/vulnerable-container:v0.0.1

      - name: lw-scanner
        uses: ./
        env:
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_SCANNER_SAVE_RESULTS: false
          LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
          LW_SCANNER_DISABLE_UPDATES: true
        with:
          image_name: ghcr.io/timarenz/vulnerable-container
          image_tag: v0.0.1
          fail_if_critical_vulnerabilities_found: false
          fail_if_high_vulnerabilities_found: false
          fail_if_medium_vulnerabilities_found: false
          fail_if_low_vulnerabilities_found: false
          fail_if_info_vulnerabilities_found: false
          fail_only_if_vulnerabilities_fixable: false
          save_html_report: true
          html_report_file_name: myreport.html
